### ISSUE TITLE
salsa and 3ddna: missing output/ and output_for_curation/ output folders in template

### ISSUE THREAD

**Issue by AlesBucek** [yoshihikosuzuki/ant-asm-workflow#6]
Hi Yoshi,
YaHS is creating two folders output/ and output_for_curation/  but salsa and 3ddna not, so they seem to stop after not finding these output folders with messages. 
```
Writing expected
Writing norms
Finished writing norms
/var/spool/slurmd/job33238325/slurm_script: line 106: cd: output_for_curation/: No such file or directory
/var/spool/slurmd/job33238325/slurm_script: line 114: ./remove_tmp_files.sh: No such file or directory
```

**Comment by yoshihikosuzuki** [comment]
Hi Ales,

Thanks for the bug report. I just added `mkdir output && mkdir output_for_curation` to `run_3ddna.sh` and `run_salsa.sh`.
It should work without errors now.

Best,
Yosho
